{% set name = "configurable-http-proxy" %}
{% set version = "5.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: a6d661f9d19507a4dc9c59976e580dc12eae541f36fa7e1abd8ee70218aea5b8

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - configurable-http-proxy -h
    - test -f $PREFIX/bin/configurable-http-proxy  # [not win]
    - if not exist %PREFIX%\\configurable-http-proxy exit 1    # [win]

about:
  home: https://github.com/jupyterhub/configurable-http-proxy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: node-http-proxy plus a REST API

extra:
  recipe-maintainers:
    - minrk
    - willingc
