{% set name = "configurable-http-proxy" %}
{% set version = "5.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: fc9ae70ec19843e9fb1c4f37aad9c9cf12c392b4d2476d60df618578be20e308

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - configurable-http-proxy -h
    - test -f $PREFIX/bin/configurable-http-proxy  # [not win]
    - if not exist %PREFIX%\\configurable-http-proxy exit 1    # [win]

about:
  home: https://github.com/jupyterhub/configurable-http-proxy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: node-http-proxy plus a REST API

extra:
  recipe-maintainers:
    - minrk
    - willingc
