{% set name = "configurable-http-proxy" %}
{% set version = "4.5.3" %}
{% set build = 0 %}

{% if not nodejs %}
# rerender doesn't always pull node value from conda_build_config on first pass
# this value will never be used in a real build
{% set nodejs = 1 %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: 774f3d8fba5bbfc198521dcc633423ef517df14d241f68a62c2486f427b033cf

build:
  number: {{ build }}
  string: node{{ nodejs }}_h{{ PKG_HASH }}_{{ build }}
  script:
    - npm pack  # [not win]
    - NPM_CONFIG_USERCONFIG=/tmp/nonexistentrc npm install -g {{ name }}-{{ version }}.tgz  # [not win]

requirements:
  host:
    - nodejs
  run:
    - nodejs

test:
  commands:
    - configurable-http-proxy -h
    - test -f $PREFIX/bin/configurable-http-proxy  # [not win]
    - if not exist %PREFIX%\\configurable-http-proxy exit 1    # [win]

about:
  home: https://github.com/jupyterhub/configurable-http-proxy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: node-http-proxy plus a REST API

extra:
  recipe-maintainers:
    - minrk
    - willingc
