provider:
  linux_aarch64: default
build_platform:
  linux_aarch64: linux_64
conda_forge_output_validation: true
bot:
  automerge: true
test_on_native_only: true
github:
  branch_name: main
  tooling_branch_name: main
